language: node_js
node_js:
  - "6"
addons:
  postgresql: "9.4"
services:
  - postgresql
sudo: false
script: "gulp coverage && npm run test:api"
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
notifications:
  email: false
